general:
  logging_level: INFO
# CRITICAL
# ERROR
# WARNING
# INFO
# DEBUG
# NOTSET
parameters:
  w: 0.8
  c_1: 1
  c_2: 0.5
  # w: 0.6
  # c_1: 2
  # c_2: 2
  num_particles: 80
  num_iterations: 200 # Number of generations
  eid: 1
  # objective_name: "RosenbrockFunction"
  topology: "FullyConnectedTopology"
  objective_name: "RosenbrockFunction"
